### ISSUE TITLE
Error with floating point exception

### ISSUE THREAD

**Issue by rahbz** [dpryan79/PileOMeth#24]
Hi, 

I am getting this error while running. 
PileOMeth extract --CHG --CHH  ~/whole_genome_TAIR10/TAIR10_all.fa 32338_CTTGTA_C89J6ANXX_3_20160105B_20160105_2.modified.bam

writing to prefix:'32338_CTTGTA_C89J6ANXX_3_20160105B_20160105_2.modified'
Floating point exception

How can I fix this?

**Comment by dpryan79** [comment]
Can you try the most recent version (0.1.12)? I suspect this is related to #23, which is fixed in that release.

**Comment by dpryan79** [comment]
If that doesn't fix it, can you provide me with the BAM file? I can debug this and release a fixed version then.

**Comment by rahbz** [comment]
Hi, 
I am using the recent version
./PileOMeth --version
0.1.12-dirty (using HTSlib version 1.2.1)

Yes sure! Here is the bam file
https://drive.google.com/file/d/0B9AIw0gsTy_zNkxuUWk4aVlndW8/view?usp=sharing

Thanks!

**Comment by dpryan79** [comment]
I can't seem to reproduce this locally with 0.1.12. Can you recompile with `make install OPTS="-g -O0" ...` and then rerun it in gdb (`gdb --args PileOMeth extract --CHG --CHH ~/whole_genome_TAIR10/TAIR10_all.fa 32338_CTTGTA_C89J6ANXX_3_20160105B_20160105_2.modified.bam`)? Presumably that'll produce the same exception and you can then type `bt` to get a backtrace.

**Comment by rahbz** [comment]
Recompiling didnt solve the issue! 
Here is the error with gdb
gdb -args ~/Softwares/PileOMeth/newCompile/PileOMeth extract --CHG --CHH ~/whole_genome_TAIR10/TAIR10_all.fa 36841_GCCAAT_C92VAANXX_1_20160229B_20160229.modified.bam
GNU gdb (GDB) 7.5.1
Copyright (C) 2012 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /home/GMI/rahul.pisupati/Softwares/PileOMeth/newCompile/PileOMeth...done.
(gdb) run
Starting program: ~/Softwares/PileOMeth/newCompile/PileOMeth extract --CHG --CHH /home/GMI/rahul.pisupati/whole_genome_TAIR10/TAIR10_all.fa 36841_GCCAAT_C92VAANXX_1_20160229B_20160229.modified.bam
warning: no loadable sections found in added symbol-file system-supplied DSO at 0x2aaaaaacb000
warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
writing to prefix:'36841_GCCAAT_C92VAANXX_1_20160229B_20160229.modified'

Program received signal SIGFPE, Arithmetic exception.
0x000000000040fc0a in faidx_fetch_seq (fai=0x4702a0, c_name=0x4f2390 "Chr1", p_beg_i=-1, p_end_i=-1, len=0x7fffffff2b5c) at faidx.c:455
455	    int ret = bgzf_useek(fai->bgzf, val.offset + p_beg_i / val.line_blen * val.line_len + p_beg_i % val.line_blen, SEEK_SET);
(gdb) next

Program terminated with signal SIGFPE, Arithmetic exception.
The program no longer exists.

**Comment by dpryan79** [comment]
This appears to be an issue with the fasta file. Can you post that somewhere?

**Comment by rahbz** [comment]
This is the TAIR10 arabidopsis genome file. Anyway I have uploaded it in here 
https://drive.google.com/file/d/0B9AIw0gsTy_zTW9oVS1SZjg4S0U/view?usp=sharing

**Comment by rahbz** [comment]
I think I figured this out. I chop the header to just the chromosome name (removing the rest) and indexing it again. It gave me no error. I dont know why that is the case. 

Thank you!! 
Rahul

**Comment by dpryan79** [comment]
Weird stuff, don't know why that caused an issue either but glad it's working now :)
